apiVersion: v1
kind: Service
metadata:
  name: cloud-native-go
  labels:
    app: cloud-native-go
spec:
  # use NodePort here to be able to access the port on each node
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: cloud-native-go
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-native-go
spec:
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: cloud-native-go
    spec:
      containers:
      - name: cloud-native-go
        image: "cloud-native-go:1.0.1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          timeoutSeconds: 5
